[project]
name = "sarcomfasttrack-be"
version = "0.1.0"
description = "Backend for SarcomFasttrack"
requires-python = ">=3.11"
dependencies = [
    "fastapi",
    "uvicorn",
    "pydantic-settings",
    "psycopg[binary]",
    "sqlmodel",
    "python-jose[cryptography]",
    "passlib",
    "alembic",
    "fhirpy",
    "fhir.resources",
    "intersystems-irispython",
    "sentence-transformers",
    "psycopg2>=2.9.11",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
# Uncomment to pin a specific Python version for uv-managed venvs
# python-preference = "system"

[tool.hatch.build.targets.wheel]
packages = ["app"]
