apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: mongodb
  template:
    metadata:
      labels:
        pod: mongodb
    spec:
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: mongo-pvc
      containers:
        - name: mongodb
          image: mongo:7
          imagePullPolicy: Always
          ports:
            - name: mongodb
              containerPort: 27017
          volumeMounts:
            - name: db-data
              mountPath: /data/db
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-auth
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-auth
                  key: password
          resources:
            requests:
              memory: "256Mi"
              cpu: "0.05"
            limits:
              memory: "1Gi"
              cpu: "0.5"
