apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - openapi-ui.service.yaml

configMapGenerator:
  - name: sarcoma-fasttrack-api-config
    literals:
      - database=sarcoma-fasttrack
      - collection=state

labels:
  - pairs:
      app.kubernetes.io/name: sarcoma-fasttrack-api
      app.kubernetes.io/component: webapi
      wac-fiit.github.io/component: backend
